hosts:
  frontend-host:
    ssh:
      target: localhost
    appDir: /tmp/tinyship-demo/frontend
    rsync:
      - package.json
      - package-lock.json
      - ecosystem.config.cjs
      - tinyship.config.yml

  backend-host:
    ssh:
      target: localhost
    appDir: /tmp/tinyship-demo/backend
    rsync:
      - package.json
      - package-lock.json
      - ecosystem.config.cjs
      - tinyship.config.yml

  staging-host:
    ssh:
      target: localhost
    appDir: /tmp/tinyship-demo/staging
    ecosystem: ecosystem.staging.config.cjs
    rsync:
      - package.json
      - package-lock.json
      - ecosystem.staging.config.cjs
      - tinyship.config.yml

services:
  tinyship-demo-user:
    host: frontend-host
    rsync:
      - apps/user/package.json
      - apps/user/dist
      - apps/user/.env.production
    npmInstall: true
    pm2Restart: true
    postCommand: []
  tinyship-demo-admin:
    host: frontend-host
    rsync:
      - apps/admin/package.json
      - apps/admin/dist
      - apps/admin/.env.production
    npmInstall: true
    pm2Restart: true
    postCommand: []
  tinyship-demo-backend:
    host: backend-host
    rsync:
      - apps/backend/package.json
      - apps/backend/dist
      - apps/backend/.env.production
    npmInstall: true
    pm2Restart: true
    postCommand: []
  staging-tinyship-demo-user:
    host: staging-host
    pm2App: tinyship-demo-user
    rsync:
      - apps/user/package.json
      - apps/user/dist
      - apps/user/.env.staging
    npmInstall: true
    pm2Restart: true
    postCommand: []
