hosts:
  frontend-host:
    ssh:
      target: localhost
    appDir: /tmp/tinyship-demo/frontend
    rsync:
      - dist/
      - package.json
      - package-lock.json
      - ecosystem.config.cjs
      - tinyship.config.yml
      - .env.prod.tinyship-demo-user
      - .env.prod.tinyship-demo-admin

  backend-host:
    ssh:
      target: localhost
    appDir: /tmp/tinyship-demo/backend
    rsync:
      - dist/
      - package.json
      - package-lock.json
      - ecosystem.config.cjs
      - tinyship.config.yml
      - .env.prod.tinyship-demo-backend

services:
  tinyship-demo-user:
    host: frontend-host
    npmInstall: true
    pm2Restart: true
    postCommand: []
  tinyship-demo-admin:
    host: frontend-host
    npmInstall: true
    pm2Restart: true
    postCommand: []
  tinyship-demo-backend:
    host: backend-host
    npmInstall: true
    pm2Restart: true
    postCommand: []
