hosts:
  frontend-host:
    ssh:
      target: localhost
    appDir: /tmp/tinyship-demo/frontend
    rsync:
      - apps/user/
      - apps/admin/
      - apps/user/.env.production
      - apps/admin/.env.production
      - package.json
      - package-lock.json
      - ecosystem.config.cjs
      - tinyship.config.yml

  backend-host:
    ssh:
      target: localhost
    appDir: /tmp/tinyship-demo/backend
    rsync:
      - apps/backend/
      - apps/backend/.env.production
      - package.json
      - package-lock.json
      - ecosystem.config.cjs
      - tinyship.config.yml

services:
  tinyship-demo-user:
    host: frontend-host
    npmInstall: true
    pm2Restart: true
    postCommand: []
  tinyship-demo-admin:
    host: frontend-host
    npmInstall: true
    pm2Restart: true
    postCommand: []
  tinyship-demo-backend:
    host: backend-host
    npmInstall: true
    pm2Restart: true
    postCommand: []
